long bitMatch(long, long);
long test_bitMatch(long, long);
long anyOddBit(long);
long test_anyOddBit(long);
long ezThreeFourths(long);
long test_ezThreeFourths(long);
long bitMask(long, long);
long test_bitMask(long, long);
long howManyBits(long);
long test_howManyBits(long);
long hexAllLetters(long);
long test_hexAllLetters(long);
long tmax(void);
long test_tmax(void);
long isTmin(long);
long test_isTmin(long);
long isNegative(long);
long test_isNegative(long);
long integerLog2(long);
long test_integerLog2(long);
int floatFloat2Int(unsigned);
int test_floatFloat2Int(unsigned);
unsigned floatScale1d4(unsigned);
unsigned test_floatScale1d4(unsigned);
unsigned floatNegate(unsigned);
unsigned test_floatNegate(unsigned);
